server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8085

  cloud:
    gateway:
      routes:
        - id: User-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**  # Ensure this matches the incoming request path
          filters:
            - AddRequestHeader=Access-Control-Allow-Origin, "*"  # Allow all origins
            - AddRequestHeader=Access-Control-Allow-Methods, "GET, POST, PUT, DELETE"
            - RewritePath=/users/(?<segment>.*), /${segment}  # Optional: Rewriting path before forwarding


        - id: Hotel-Service
          uri: http://localhost:8082
          predicates:
            - Path=/hotels/**

        - id: Rating-Service
          uri: http://localhost:8083
          predicates:
            - Path=/ratings/**

#eureka:
#  instances:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG